declare namespace Lib.element {
/**
 * 游戏内自定义的content
 * 来源：lib.element.content
 */
interface Content {
    chooseToDuiben(): any;
    chooseToPSS(): any;
    cardsDiscard(): any;
    chooseToEnable(): any;
    chooseToDisable(): any;
    swapEquip(): any;
    disableEquip(): any;
    enableEquip(): any;
    disableJudge(): any;
    /*----分界线----*/
    phasing(): any;
    toggleSubPlayer(): any;
    exitSubPlayer(): any;
    callSubPlayer(): any;
    reverseOrder(): any;
    addJudgeCard(): any;
    equipCard(): any;
    gameDraw(): any;
    phaseLoop(): any;
    loadPackage(): any;
    loadMode(): any;
    forceOver(): any;
    arrangeTrigger(): any;
    createTrigger(): any;
    playVideoContent(): any;
    waitForPlayer(): any;
    replaceHandcards(): any;
    replaceHandcardsOL(): any;
    phase(): any;
    phaseJudge(): any;
    phaseDraw(): any;
    phaseUse(): any;
    phaseDiscard(): any;
    chooseToUse(): any;
    chooseToRespond(): any;
    chooseToDiscard(): any;
    chooseToCompareMultiple(): any;
    chooseToCompare(): any;
    chooseSkill(): any;
    discoverCard(): any;
    chooseButton(): any;
    chooseCardOL(): any;
    chooseButtonOL(): any;
    chooseCard(): any;
    chooseTarget(): any;
    chooseCardTarget(): any;
    chooseControl(): any;
    chooseBool(): any;
    chooseDrawRecover(): any;
    choosePlayerCard(): any;
    discardPlayerCard(): any;
    gainPlayerCard(): any;
    showHandcards(): any;
    showCards(): any;
    viewCards(): any;
    moveCard(): any;
    useCard(): any;
    useSkill(): any;
    draw(): any;
    discard(): any;
    respond(): any;
    swapHandcards(): any;
    gainMultiple(): any;
    gain(): any;
    lose(): any;
    damage(): any;
    recover(): any;
    loseHp(): any;
    doubleDraw(): any;
    loseMaxHp(): any;
    gainMaxHp(): any;
    changeHp(): any;
    changeHujia(): any;
    dying(): any;
    die(): any;
    equip(): any;
    addJudge(): any;
    judge(): any;
    turnOver(): any;
    link(): any;
}
}