declare namespace Lib.element {

    /**
     * 玩家类
     * 还有许多内部属性没暴露出来
     * 来源：lib.element.player
     */
    interface Player {
        //新函数
        chooseToDuiben(target: any): any;
        chooseToPSS(target: any): any;
        chooseToEnable(): any;
        chooseToDisable(horse: any): any;
        countDisabled(): any;
        isPhaseUsing(notmeisok: any): any;
        swapEquip(target: any): any;
        canCompare(target: any): any;
        disableEquip(pos: any): any;
        $disableEquip(skill: any): any;
        enableEquip(pos: any): any;
        $enableEquip(skill: any): any;
        isDisabled(arg: any): any;
        isEmpty(num: any): any;
        disableJudge(): any;
        //原有函数
        init(character: any, character2: any, skill: any): any;
        initOL(name: any, character: any): any;
        uninitOL(): any;
        initRoom(info: any, info2: any): any;
        reinit(from: any, to: any, maxHp: any, online: any): any;
        uninit(): any;
        getLeft(): any;
        getTop(): any;
        smoothAvatar(vice: any, video: any): any;
        changeSeat(position: any, video: any): any;
        send(): any;
        getId(): any;
        chat(str: any): any;
        say(str: any): any;
        showGiveup(): any;
        applySkills(skills: any): any;
        getState(): any;
        setNickname(str: any): any;
        setAvatar(name: any, name2: any, video: any, fakeme: any): any;
        setAvatarQueue(name: any, list: any): any;
        flashAvatar(skill: any, name: any): any;
        update(): any;
        updateMark(i: any, storage: any): any;
        updateMarks(connect: any): any;
        num(arg1: any, arg2: any, arg3: any): any;
        line(target: any, config: any): any;
        line2(targets: any, config: any): any;
        getNext(): any;
        getPrevious(): any;
        countUsed(card: any): any;
        countSkill(skill: any): any;
        getStockSkills(unowned: any, unique: any, hidden: any): any;
        getCards(arg1: any, arg2: any): any;
        getDiscardableCards(player: any, arg1: any, arg2: any): any;
        getGainableCards(player: any, arg1: any, arg2: any): any;
        getGainableSkills(func: any): any;
        countCards(arg1: any, arg2: any): any;
        countDiscardableCards(player: any, arg1: any, arg2: any): any;
        countGainableCards(player: any, arg1: any, arg2: any): any;
        getOriginalSkills(): any;
        getSkills(arg2: any, arg3: any, arg4: any): any;
        get(arg1: any, arg2: any, arg3: any, arg4: any): any;
        syncStorage(skill: any): any;
        syncSkills(): any;
        playerfocus(time: any): any;
        setIdentity(identity: any): any;
        insertPhase(skill: any, insert: any): any;
        insertEvent(name: any, content: any, arg: any): any;
        phase(skill: any): any;
        phaseJudge(): any;
        phaseDraw(): any;
        phaseUse(): any;
        phaseDiscard(): any;
        chooseToUse(use: any): any;
        chooseToRespond(): any;
        chooseToDiscard(): any;
        chooseToCompare(target: any, check: any): any;
        chooseSkill(target: any): any;
        discoverCard(list: any): any;
        chooseCardButton(): any;
        chooseVCardButton(): any;
        chooseButton(): any;
        chooseButtonOL(list: any, callback: any, ai: any): any;
        chooseCardOL(): any;
        chooseCard(): any;
        chooseUseTarget(card: any, prompt: any, includecard: any): any;
        chooseTarget(): any;
        chooseCardTarget(choose: any): any;
        chooseControlList(): any;
        chooseControl(): any;
        chooseBool(): any;
        chooseDrawRecover(): any;
        choosePlayerCard(): any;
        discardPlayerCard(): any;
        gainPlayerCard(): any;
        showHandcards(str: any): any;
        showCards(cards: any, str: any): any;
        viewCards(str: any, cards: any): any;
        viewHandcards(target: any): any;
        canMoveCard(withatt: any): any;
        moveCard(): any;
        useResult(result: any, event: any): any;
        useCard(): any;
        useSkill(): any;
        draw(): any;
        randomDiscard(): any;
        randomGain(): any;
        discard(): any;
        respond(): any;
        swapHandcards(target: any, cards1: any, cards2: any): any;
        directequip(cards: any): any;
        directgain(cards: any): any;
        gainMultiple(targets: any, position: any): any;
        gain(): any;
        give(cards: any, target: any, visible: any): any;
        lose(): any;
        damage(): any;
        recover(): any;
        doubleDraw(): any;
        loseHp(num: any): any;
        loseMaxHp(): any;
        gainMaxHp(): any;
        changeHp(num: any, popup: any): any;

        changeHujia(num: any, type: any): any;
        getBuff(): any;
        getDebuff(): any;
        dying(reason: any): any;
        die(reason: any): any;
        revive(hp: any, log: any): any;
        isMad(): any;
        goMad(end: any): any;
        unMad(): any;
        tempHide(): any;
        addExpose(num: any): any;
        equip(card: any, draw: any): any;
        addJudge(card: any, cards: any): any;
        canAddJudge(card: any): any;
        addJudgeNext(card: any): any;
        judge(): any;
        turnOver(bool: any): any;
        out(skill: any): any;
        in(skill: any): any;
        link(bool: any): any;
        skip(name: any): any;
        wait(callback: any): any;
        unwait(result: any): any;
        logSkill(name: any, targets: any, nature: any, logv: any): any;
        unprompt(): any;
        prompt(str: any, nature: any): any;
        prompt_old(name2: any, className: any): any;
        popup(name: any, className: any): any;
        popup_old(name: any, className: any): any;
        _popup(): any;
        showTimer(time: any): any;
        hideTimer(): any;
        markSkill(name: any, info: any, card: any): any;
        unmarkSkill(name: any): any;
        markSkillCharacter(id: any, target: any, name: any, content: any): any;
        markCharacter(name: any, info: any, learn: any, learn2: any): any;
        mark(name: any, info: any, skill: any): any;
        unmark(name: any, info: any): any;
        addLink(): any;
        removeLink(): any;
        canUse(card: any, target: any, distance: any, includecard: any): any;
        hasUseTarget(card: any, distance: any, includecard: any): any;
        getUseValue(card: any, distance: any, includecard: any): any;
        addSubPlayer(cfg: any): any;
        removeSubPlayer(name: any): any;
        callSubPlayer(): any;
        toggleSubPlayer(): any;
        exitSubPlayer(remove: any): any;
        getSubPlayers(tag: any): any;
        /**
         * 增加技能触发
         * @param skill 技能名
         * @param hidden 
         * @param triggeronly 
         */
        addSkillTrigger(skill: string, hidden: boolean, triggeronly?: boolean): any;
        addSkillLog(skill: any): any;
        addSkill(skill: any, checkConflict: any, nobroadcast: any): any;
        addAdditionalSkill(skill: any, skills: any, keep: any): any;
        removeAdditionalSkill(skill: any, target: any): any;
        awakenSkill(skill: any, nounmark: any): any;
        restoreSkill(skill: any, nomark: any): any;
        disableSkill(skill: any, skills: any): any;
        enableSkill(skill: any): any;
        checkMarks(): any;
        addEquipTrigger(card: any): any;
        removeEquipTrigger(card: any): any;
        removeSkillTrigger(skill: any, triggeronly: any): any;
        /** 玩家失去技能/移除玩家的技能 */
        removeSkill(skill: any | any[], flag?: boolean): any;
        addTempSkill(skill: any, expire: any, checkConflict: any): any;
        attitudeTo(target: any): any;
        clearSkills(all: any): any;
        checkConflict(skill: any): any;
        getStat(key: any): any;
        queue(time: any): any;
        getCardUsable(card: any, pure: any): any;
        getAttackRange(raw: any): any;
        getGlobalFrom(): any;
        getGlobalTo(): any;
        getHandcardLimit(): any;
        getEnemies(func: any): any;
        getFriends(func: any): any;
        isEnemyOf(): any;
        isFriendOf(player: any): any;
        isFriendsOf(player: any): any;
        isEnemiesOf(player: any): any;
        isAlive(): any;
        isDead(): any;
        isDying(): any;
        isDamaged(): any;
        isHealthy(): any;
        isMaxHp(equal: any): any;
        isMinHp(equal: any): any;
        isMaxCard(equal: any): any;
        isMinCard(equal: any): any;
        isMaxHandcard(equal: any): any;
        isMinHandcard(equal: any): any;
        isMaxEquip(equal: any): any;
        isMinEquip(equal: any): any;
        isLinked(): any;
        isTurnedOver(): any;
        isOut(): any;
        isMin(distance: any): any;
        isIn(): any;
        isUnseen(num: any): any;
        isUnderControl(self: any, me: any): any;
        isOnline(): any;
        isOnline2(): any;
        isOffline(): any;
        checkShow(skill: any, showonly: any): any;
        needsToDiscard(num: any): any;
        distanceTo(target: any, method: any): any;
        distanceFrom(target: any, method: any): any;
        hasSkill(skill: any, arg2: any, arg3: any, arg4: any): any;
        hasStockSkill(skill: any, arg1: any, arg2: any, arg3: any): any;
        hasZhuSkill(skill: any, player: any): any;
        hasGlobalTag(tag: any, arg: any): any;
        hasSkillTag(tag: any, hidden: any, arg: any, globalskill: any): any;
        hasJudge(name: any): any;
        hasFriend(): any;
        hasUnknown(num: any): any;
        isUnknown(player: any): any;
        hasWuxie(): any;
        hasSha(respond: any, noauto: any): any;
        hasShan(): any;
        mayHaveShan(): any;
        hasCard(name: any, position: any): any;
        canEquip(name: any, replace: any): any;
        getEquip(name: any): any;
        getJudge(name: any): any;
        $drawAuto(cards: any, target: any): any;
        $draw(num: any, init: any, config: any): any;
        $compareMultiple(card1: any, targets: any, cards: any): any;
        $compare(card1: any, target: any, card2: any): any;
        $throw(card: any, time: any, init: any, nosource: any): any;
        $throwordered(): any;
        $throwordered1(node: any, nosource: any): any;
        $throwordered2(node: any, nosource: any): any;
        $throwxy(card: any, left: any, top: any): any;
        $throwxy2(card: any, left: any, top: any, trans: any, flipx: any, flipy: any): any;
        throwDice(num: any): any;
        $giveAuto(card: any, player: any): any;
        $give(card: any, player: any, log: any, init: any): any;
        $equip(card: any): any;
        $gain(card: any, log: any, init: any): any;
        $gain2(cards: any, log: any): any;
        $skill(name: any, type: any, color: any, avatar: any): any;
        $fire(): any;
        $thunder(): any;
        $rare2(): any;
        $epic2(): any;
        $legend2(): any;
        $rare(time: any): any;
        $epic(time: any): any;
        $legend(time: any): any;
        $coin(): any;
        $dust(): any;
        $recover(): any;
        $fullscreenpop(str: any, nature: any, avatar: any): any;
        $damagepop(num: any, nature: any, font: any): any;
        $damage(source: any): any;
        $die(): any;
        $dieflip(type: any): any;
        $phaseJudge(card: any): any;
    }
}