declare var ui:UI;
interface UI {
    updates:[],
    thrown:[],
    touchlines:[],
    todiscard:{},
    refresh(node):any;
    create:UI.Create,
    click:UI.Click,
    selected:{
        buttons:[],
        cards:[],
        targets:[]
    },
    clear():any;
    updatec():any;
    updatex():any;
    updatexr():any;
    updatejm(player,nodes,start,inv):any;
    updatem(player):any;
    updatej(player):any;
    updatehl():any;
    updateh(compute):any;
    updatehx(node):any;
    updated():any;
    updatez():any;
    update():any;
    recycle(node,key):any;
}