game.import("extension",function(lib,game,ui,get,ai,_status){return {name:"聊天表情",content:function (config,pack){
    
},precontent:function (){
	var expressionList={
		'shibing':{
			image:'http://club.sanguosha.com/static/image/smiley/vip_smile/13.gif',
			contains:{
				'1':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/1.gif',
					width:'50',
					height:'50',
				},
				'2':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/2.gif',
					width:'50',
					height:'50',
				},
				'3':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/3.gif',
					width:'50',
					height:'50',
				},
				'4':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/4.gif',
					width:'50',
					height:'50',
				},
				'5':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/5.gif',
					width:'50',
					height:'50',
				},
				'6':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/6.gif',
					width:'50',
					height:'50',
				},
				'7':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/7.gif',
					width:'50',
					height:'50',
				},
				'8':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/8.gif',
					width:'50',
					height:'50',
				},
				'9':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/9.gif',
					width:'50',
					height:'50',
				},
				'10':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/10.gif',
					width:'50',
					height:'50',
				},
				'11':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/11.gif',
					width:'50',
					height:'50',
				},
				'12':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/12.gif',
					width:'50',
					height:'50',
				},
				'13':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/13.gif',
					width:'50',
					height:'50',
				},
				'14':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/14.gif',
					width:'50',
					height:'50',
				},
				'15':{
					src:'http://club.sanguosha.com/static/image/smiley/vip_smile/15.gif',
					width:'50',
					height:'50',
				},
			},
		},
		'guojia':{
			image:'http://club.sanguosha.com/static/image/smiley/guojia/9.gif',
			contains:{
				'1':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/1.gif',
					width:'50',
					height:'50',
				},
				'2':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/2.gif',
					width:'50',
					height:'50',
				},
				'3':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/3.gif',
					width:'50',
					height:'50',
				},
				'4':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/4.gif',
					width:'50',
					height:'50',
				},
				'5':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/5.gif',
					width:'50',
					height:'50',
				},
				'6':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/6.gif',
					width:'50',
					height:'50',
				},
				'7':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/7.gif',
					width:'50',
					height:'50',
				},
				'8':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/8.gif',
					width:'50',
					height:'50',
				},
				'9':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/9.gif',
					width:'50',
					height:'50',
				},
				'10':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/10.gif',
					width:'50',
					height:'50',
				},
				'11':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/11.gif',
					width:'50',
					height:'50',
				},
				'12':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/12.gif',
					width:'50',
					height:'50',
				},
				'13':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/13.gif',
					width:'50',
					height:'50',
				},
				'14':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/14.gif',
					width:'50',
					height:'50',
				},
				'15':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/15.gif',
					width:'50',
					height:'50',
				},
				'16':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/16.gif',
					width:'50',
					height:'50',
				},
				'17':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/17.gif',
					width:'50',
					height:'50',
				},
				'18':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/18.gif',
					width:'50',
					height:'50',
				},
				'19':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/19.gif',
					width:'50',
					height:'50',
				},
				'20':{
					src:'http://club.sanguosha.com/static/image/smiley/guojia/20.gif',
					width:'50',
					height:'50',
				},
			},
		},
		'chicken':{
			image:'http://club.sanguosha.com/static/image/smiley/chicken/7.gif',
			contains:{
				'1':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/1.gif',
					width:'50',
					height:'50',
				},
				'2':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/2.gif',
					width:'50',
					height:'50',
				},
				'3':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/3.gif',
					width:'50',
					height:'50',
				},
				'4':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/4.gif',
					width:'50',
					height:'50',
				},
				'5':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/5.gif',
					width:'50',
					height:'50',
				},
				'6':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/6.gif',
					width:'50',
					height:'50',
				},
				'7':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/7.gif',
					width:'50',
					height:'50',
				},
				'8':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/8.gif',
					width:'50',
					height:'50',
				},
				'9':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/9.gif',
					width:'50',
					height:'50',
				},
				'10':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/10.gif',
					width:'50',
					height:'50',
				},
				'11':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/11.gif',
					width:'50',
					height:'50',
				},
				'12':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/12.gif',
					width:'50',
					height:'50',
				},
				'13':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/13.gif',
					width:'50',
					height:'50',
				},
				'14':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/14.gif',
					width:'50',
					height:'50',
				},
				'15':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/15.gif',
					width:'50',
					height:'50',
				},
				'16':{
					src:'http://club.sanguosha.com/static/image/smiley/chicken/16.gif',
					width:'50',
					height:'50',
				},
			},
		},
		'diaocan':{
			image:'http://club.sanguosha.com/static/image/smiley/diaocan/8.jpg',
			contains:{
				'1':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/1.jpg',
					width:'50',
					height:'50',
				},
				'2':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/2.jpg',
					width:'50',
					height:'50',
				},
				'3':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/3.jpg',
					width:'50',
					height:'50',
				},
				'4':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/4.jpg',
					width:'50',
					height:'50',
				},
				'5':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/5.jpg',
					width:'50',
					height:'50',
				},
				'6':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/6.jpg',
					width:'50',
					height:'50',
				},
				'8':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/8.jpg',
					width:'50',
					height:'50',
				},
				'9':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/9.jpg',
					width:'50',
					height:'50',
				},
				'10':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/10.jpg',
					width:'50',
					height:'50',
				},
				'11':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/11.jpg',
					width:'50',
					height:'50',
				},
				'12':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/12.jpg',
					width:'50',
					height:'50',
				},
				'13':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/13.jpg',
					width:'50',
					height:'50',
				},
				'14':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/14.jpg',
					width:'50',
					height:'50',
				},
				'15':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/15.jpg',
					width:'50',
					height:'50',
				},
				'16':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/16.jpg',
					width:'50',
					height:'50',
				},
				'17':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/17.jpg',
					width:'50',
					height:'50',
				},
				'18':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/18.jpg',
					width:'50',
					height:'50',
				},
				'19':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/19.jpg',
					width:'50',
					height:'50',
				},
				'20':{
					src:'http://club.sanguosha.com/static/image/smiley/diaocan/20.jpg',
					width:'50',
					height:'50',
				},
			},
		},
		'zhenji':{
			image:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji11.gif',
			contains:{
				'10':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji10.gif',
					width:'50',
					height:'50',
				},
				'11':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji11.gif',
					width:'50',
					height:'50',
				},
				'12':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji12.gif',
					width:'50',
					height:'50',
				},
				'13':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji13.gif',
					width:'50',
					height:'50',
				},
				'14':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji14.gif',
					width:'50',
					height:'50',
				},
				'15':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji15.gif',
					width:'50',
					height:'50',
				},
				'16':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji16.gif',
					width:'50',
					height:'50',
				},
				'17':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji17.gif',
					width:'50',
					height:'50',
				},
				'18':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji18.gif',
					width:'50',
					height:'50',
				},
				'19':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji19.gif',
					width:'50',
					height:'50',
				},
				'20':{
					src:'http://club.sanguosha.com/static/image/smiley/zhenji/zhenji20.gif',
					width:'50',
					height:'50',
				},
			},
		},
		'wanglang':{
			image:'http://club.sanguosha.com/static/image/smiley/wanglang/5.gif',
			contains:{
				'1':{
					src:'http://club.sanguosha.com/static/image/smiley/wanglang/1.gif',
					width:'50',
					height:'50',
				},
				'2':{
					src:'http://club.sanguosha.com/static/image/smiley/wanglang/2.gif',
					width:'50',
					height:'50',
				},
				'3':{
					src:'http://club.sanguosha.com/static/image/smiley/wanglang/3.gif',
					width:'50',
					height:'50',
				},
				'4':{
					src:'http://club.sanguosha.com/static/image/smiley/wanglang/4.gif',
					width:'50',
					height:'50',
				},
				'5':{
					src:'http://club.sanguosha.com/static/image/smiley/wanglang/5.gif',
					width:'50',
					height:'50',
				},
			},
		},
	};
            ui.click.chat=function(){
                ui.system1.classList.add('shown');
                ui.system2.classList.add('shown');

                var uiintro=ui.create.dialog('hidden');
				uiintro.listen(function(e){
					e.stopPropagation();
				});

                var list=ui.create.div('.caption');
                if(get.is.phoneLayout()){
                    list.style.maxHeight='200px';
                }
                else{
                    list.style.maxHeight='300px';
                }
                list.style.overflow='scroll';
                lib.setScroll(list);
                uiintro.contentContainer.style.overflow='hidden';

                var input;
                var addEntry=function(info,clear){
                    if(list._chatempty){
                        list.innerHTML='';
                        delete list._chatempty;
                    }
                    var node=ui.create.div('.text.chat');
                    node.innerHTML=info[0]+': '+info[1];
                    list.appendChild(node);
                    list.scrollTop=list.scrollHeight;
    				uiintro.style.height=uiintro.content.scrollHeight+'px';
                }
                _status.addChatEntry=addEntry;
                _status.addChatEntry._origin=uiintro;
                if(lib.chatHistory.length){
                    for(var i=0;i<lib.chatHistory.length;i++){
                        addEntry(lib.chatHistory[i]);
                    }
                }
                else{
                    list._chatempty=true;
                    list.appendChild(ui.create.div('.text.center','无聊天记录'))
                }
                uiintro.add(list);
                uiintro.style.height=uiintro.content.offsetHeight+'px';
                list.scrollTop=list.scrollHeight;

                var node=uiintro.add('<input type="text" value="">');
                node.style.paddingTop=0;
                node.style.marginBottom='16px';
                input=node.firstChild;
                input.style.width='calc(100% - 20px)';
                input.onkeydown=function(e){
                    if(e.keyCode==13&&input.value){
                        var player=game.me;
                        var str=input.value;
                        if(!player){
                            if(game.connectPlayers){
                                if(game.online){
                                    for(var i=0;i<game.connectPlayers.length;i++){
                                        if(game.connectPlayers[i].playerid==game.onlineID){
                                            player=game.connectPlayers[i];break;
                                        }
                                    }
                                }
                                else{
                                    player=game.connectPlayers[0];
                                }
                            }
                        }
                        if(!player) return;
                        if(game.online){
                            game.send('chat',game.onlineID,str);
                        }
                        else{
                            lib.element.player.chat.call(player,str);
                        }
                        input.value='';
                    }
                    e.stopPropagation();
                }
                uiintro._onopen=function(){
                    input.focus();
                    list.scrollTop=list.scrollHeight;
                };
                uiintro._heightfixed=true;
				var expression1=ui.create.div('.text.center');
				expression1.innerHTML='快捷表情包';
				expression1.style.width='calc(100%)';
				uiintro.add(expression1);
				var list1=ui.create.div('');
				if(get.is.phoneLayout()){
					list1.style.height='100px';
				}else{
					list1.style.height='150px';
				}
				list1.style.overflow='scroll';
				uiintro.add(list1);
				uiintro.style.height=uiintro.content.offsetHeight+'px';
				var list2=ui.create.div('');
				if(get.is.phoneLayout()){
					list2.style.height='100px';
				}else{
					list2.style.height='150px';
				}
				list2.style.overflow='scroll';
				uiintro.style.height=uiintro.content.offsetHeight+'px';
				for(var i in expressionList){
					var expressionBag=ui.create.div('.card.fullskin','<img src="'+expressionList[i].image+'" width="50" height="50">',function(){
						expression1.innerHTML='快捷表情';
						for(var j in expressionList[this.link].contains){
							var road=expressionList[this.link].contains;
							var expression=ui.create.div('.card.fullskin','<img src="'+road[j].src+'" width="50" height="50">',function(){
								input.value+='<img src="'+road[this.link].src+'" width="'+road[this.link].width+'" height="'+road[this.link].height+'">';
								input.focus();
							});
							expression.link=j;
							expression.style.height='50px';
							expression.style.width='50px';
							list2.appendChild(expression);
						};
						list1.delete();
						uiintro.add(list2);
					});
					expressionBag.link=i;
					expressionBag.style.height='50px';
					expressionBag.style.width='50px';
					list1.appendChild(expressionBag);
				};
                return uiintro;
            };
},config:{},help:{},package:{
    character:{
        character:{
        },
        translate:{
        },
    },
    card:{
        card:{
        },
        translate:{
        },
        list:[],
    },
    skill:{
        skill:{
        },
        translate:{
        },
    },
},files:{"character":[],"card":[],"skill":[]}}})